export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const CREATE_POST = 'CREATE_POST';
export const EDITED_POST = 'EDITED_POST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const LOAD_USER = 'LOAD_USER';
export const USER_REGISTERED = 'USER_REGISTERED';

export const LOADING = 'LOADING';
export const LOCALITY_LOADING = 'LOCALITY_LOADING';
export const AUTH_LOADING = 'AUTH_LOADING';
export const ANIMALS_LOADING = 'ANIMAL_LOADING';
export const POST_LOADING = 'POST_LOADING';
export const STREET_LOADING = 'STREET_LOADING';

export const UPDATE_PIC = 'UPDATE_PIC';
export const UPLOADING = 'UPLOADING';

export const POST_REMOVED = 'POST_REMOVED';
export const ADDED_COMMENT = 'ADDED_COMMENT';
export const REMOVED_COMMENT = 'REMOVED_COMMENT';

export const GET_ALL_DATA = 'GET_ALL_DATA';
export const FETCHED_LOCALITY = 'FETCHED_LOCALITY';
export const FETCHED_STREET_DATA = 'FETCHED_STREET_DATA';
export const UPDATED_STREET_DATA = 'UPDATED_STREET_DATA';
export const STREET_UPDATED = 'STREET_UPDATED';
export const UPDATE_STREETDB = 'UPDATE_STREETDB';
export const GET_DOGS = 'GET_DOGS';
export const GET_CATS = 'GET_CATS';
export const GET_FEEDERS = 'GET_FEEDERS';
export const GET_STREET_ANIMALS = 'GET_STREET_ANIMALS';
export const GET_LOCALITY_INFO = 'GET_LOCALITY_INFO';

export const SET_CURRENT_STREET = 'SET_CURRENT_STREET';
export const DEVICE_IDENTIFIED = 'DEVICE_IDENTIFIED';

export const ANIMAL_ADDED = 'ANIMAL_ADDED';
export const ANIMAL_DELETED = 'ANIMAL_DELETED';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const FETCH_ERROR = 'FETCH_ERROR';
export const LOCALITY_ERROR = 'LOCALITY_ERROR';
export const ANIMALS_ERROR = 'ANIMALS_ERROR';
export const AUTH_ERROR = 'AUTH_ERROR';
export const POST_ERROR = 'POST_ERROR';
export const UPLOAD_ERROR = 'UPLOAD_ERROR';
